### PR TITLE
Automate report generation

### PR DESCRIPTION
**Pull request by fayanpardo**
## Description

PR with automate report generation
Now the scripts generate a plot:
image

And creates a personalized report:
image

## Related Issue

#94 
## Motivation and Context

We need to clearly show to the final user meaningful configuration of our benchmarking process
## How Has This Been Tested?

Run under bin/ python analyzer/aggregate-html-reports.py

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fayanpardo** [comment]
Things to be improved in this PR:
The size of the image in the html may be too large.
~~The html is still not saying what was the best configuration.~~
The table is ordered from worst TPS to best TPS, maybe should be the other way around.
Make the aggregate-html-reports.py more stable. I did a fast implementation and error handling should be implemented correctly.
Modify prerequisites.sh to install the R libraries the R script is using.

**Comment by ulalaa14** [comment]
also need to redefined the path. since i got the error. we have to remove the 'analyzer' string in the path. because aggregate-html-reports.py is already inside analyzer folder
image

**Comment by fayanpardo** [comment]
> also need to redefined the path. since i got the error. we have to remove the 'analyzer' string in the path. because aggregate-html-reports.py is already inside analyzer folder
> image

@ulalaa14 I added that path because we expect main.py to execute it and main script is in bin/. If you execute it in that directory it should work.

**Comment by ulalaa14** [comment]
Probably we can use this kind of chart from python library, https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.hexbin.html#pandas.DataFrame.plot.hexbin.
image

**Comment by fayanpardo** [comment]
nice catch @ulalaa14 with this it is more clear and we also avoid R.
image

**Pull request closed without merging**
