### PR TITLE
Algorithms implementation

### PR DESCRIPTION
**Pull request by fayanpardo**
## Description

Implemented algorithms #80  #77 #81 
## Related Issue

#80  #77 #81 #14 
## How Has This Been Tested?

Executed main.py. Further testing needed after merging #74

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fayanpardo** [comment]
The implementation of the minimum gas limit works. The implementation of Optibench algorithm still has an error when calculating the accuracy and it stops the benchmarking of a dimension even if there are more improvements.
A result example:
image

We anyways can see a trend in the results:
image

As discussed the more interval, the less throughput. Also the min gas limit is nearly the same no matter the interval:
3seconds-3996093.html
2seconds-3984375.html
1seconds-3992187.html

**Comment by fayanpardo** [comment]
This PR can be reviewed now.

**Comment by ulalaa14** [comment]
i got error when gcloud wanted to find ethereum template. probably any configuration i should add?
image

**Comment by fayanpardo** [comment]
> i got error when gcloud wanted to find ethereum template. probably any configuration i should add?
> image

try now after the new merge :) @ulalaa14

**Comment by ankushshr1993** [comment]
Still giving the same error 
Screenshot 2020-01-30 at 22 16 26

**Comment by fayanpardo** [comment]
> Still giving the same error
> Screenshot 2020-01-30 at 22 16 26

@ankushshr1993 your error is not related, you are missing JQ which is a requirement.

**Comment by ulalaa14** [comment]
it works if the config.json change the template name to ethereum-sut-template however while benchmarking it always failling.
image

**Comment by fayanpardo** [comment]
> it works if the config.json change the template name to ethereum-sut-template however while benchmarking it always failling.
> image

can you share a screenshot of the error that throws run-caliper.py?

**Comment by ulalaa14** [comment]
image
this one. i think it only reached the maximum tries

**Comment by fayanpardo** [comment]
But can you check what caliper is running in the status.txt file or try to run caliper alone? We need to see caliper error

**Comment by fayanpardo** [comment]
It seems that the error was originated because main.py was using sh instead of bash and when using bash, echo was not reading correctly \n characters, specifically the error was in line 96.
Fixed in last commit

**Comment by ulalaa14** [comment]
cool! it works now 👍

**Review by ulalaa14 — APPROVED** [review]
running well in my machine !

**Pull request merged**
