### PR TITLE
Was Merged as part of another PR already :updating caliper, web3, path

### PR DESCRIPTION
**Pull request by XhorxhinaT**
Caliper with locally npm installation;
Web3 install
Path fix

### CODE REVIEW

**Comment by ulalaa14** [comment]
it installed caliper & web3, however not inside bin folder

**Comment by XhorxhinaT** [comment]
> it installed caliper & web3, however not inside bin folder

@ulalaa14  was web3 supposed to be installed inside workload??

**Comment by fayanpardo** [comment]
web3 was being installed in the base dir. Caliper was being installed in bin/workload. The result was different npm workspaces. Also the binding done was of fabric and we need to bind with ethereum.

Better to install with the package.json under bin/workload.

**Comment by ulalaa14** [comment]
i think the package.json need to push into bin folder too for installing npm dependencies
image

**Comment by XhorxhinaT** [comment]
@ulalaa14  i think i will leave caliper inside workload..like logically, if the path is right in the main .py it should not cause any problem

**Comment by ulalaa14** [comment]
hmmm i think in our code, we're using caliper in bin path. if we keep it in the workload there would need changes in the code. we have to change related files to do that. however, i haven't found yet which is/are the related files. probably because the main.py is called in the bin, that's why it needs to call caliper from that directory

**Comment by XhorxhinaT** [comment]
Update finished in another PR merged

**Pull request closed without merging**
