### PR TITLE
Main error fix, print improvements and config formatting

### PR DESCRIPTION
**Pull request by fayanpardo**
## Description

This PR fixes an error in main.py when calling aggregate-html-reports.py, improves tool output and fixes config file formatting
## Related Issue

#112 
## How Has This Been Tested?

running python main.py 1 0

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ulalaa14** [comment]
image
found this error

**Comment by fayanpardo** [comment]
> image
> found this error

Not happening to me. Can you try to replicate what main is trying to execute with aggregate-html-reports.py? Maybe it can give us a more clear error.

**Comment by ulalaa14** [comment]
> > image
> > found this error
> 
> Not happening to me. Can you try to replicate what main is trying to execute with aggregate-html-reports.py? Maybe it can give us a more clear error.

sorry, i deleted that comment, i realised it wasn't the latest version of yours. my bad. currently doing the testing again

**Comment by ulalaa14** [comment]
finish and still showing this. i probably missed something. i did `python3 main.py 1 0`
image

**Review by XhorxhinaT — COMMENTED** [review]
GJ

**Review by XhorxhinaT — APPROVED** [review]
GJ

**Pull request merged**
