### PR TITLE
Aggregating reports

### PR DESCRIPTION
**Pull request by ulalaa14**
Aggregating Report

## Description
Since until now we use summary table. Don't have to worry about the rounds we will use. However split the report for each functions, it will be used to determine maximum value by other script. Also delete query function.

## Related Issue
https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/issues/36

## Motivation and Context
This change is to make separate report for each function.

## How Has This Been Tested?
Run the script aggregate-html-reports.py script. It will give the 3 reports (all functions, open function report, transfer function report)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist contributor:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by fayanpardo — COMMENTED** [review]
This is a question for @ankushshr1993 also. Are the imports in lines 3-5 really used in the script? We do no want residual code that can make our solution heavier.

**Comment by fayanpardo** [comment]
Also what are the requirements to execute this script? in order to do a compilation file in the repo or to at least document how to prepare the requirements in another task. 
Thanks!

**Comment by santosh-dhirwani** [comment]
@ankushshr1993  Could you please make the required changes, test it and share your feedback?

This PR is related to issue #36  and the deadline is today. Let me know if you need any help. Thanks!

**Comment by ankushshr1993** [comment]
Have removed and updated  the extra libraries and added a read me 
have also tested the code it's creating another 2 separate csvs for transfer and query from the primary one

**Pull request closed without merging**
